name: Build SwiftyTorrent IPA

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-14

    steps:
      #
      # Checkout
      #
      - name: Checkout
        uses: actions/checkout@v4

      #
      # Install tools
      #
      - name: Install dependencies
        run: |
          brew install carthage

      #
      # Fix dead boost URL
      #
      - name: Patch bootstrap.sh
        run: |
          perl -pi -e 's#https://boostorg\.jfrog\.io[^\s"]+#https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.gz#g' bootstrap.sh

          echo "===== BOOST URL CHECK ====="
          grep -i boost bootstrap.sh

      #
      # Cache Carthage
      #
      - name: Cache Carthage
        uses: actions/cache@v4
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-

      #
      # Bootstrap Carthage
      #
      - name: Bootstrap Carthage
        run: |
          chmod +x carthage.sh
          ./carthage.sh bootstrap --platform ios --use-xcframeworks

      #
      # Bootstrap third-party dependencies
      #
      - name: Bootstrap dependencies
        run: |
          chmod +x bootstrap.sh
          ./bootstrap.sh

      #
      # Show available schemes
      #
      - name: List schemes
        run: |
          xcodebuild -list -project SwiftyTorrent.xcodeproj

      #
      # Build app
      #
      - name: Build SwiftyTorrent
        run: |
          xcodebuild \
            -project SwiftyTorrent.xcodeproj \
            -scheme SwiftyTorrent \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            OTHER_CPLUSPLUSFLAGS="-std=c++14"

      #
      # Create IPA
      #
      - name: Create IPA
        run: |
          mkdir Payload

          APP_PATH=$(find build -name "*.app" | head -n 1)

          echo "APP_PATH=$APP_PATH"

          cp -R "$APP_PATH" Payload/

          zip -r SwiftyTorrent.ipa Payload

      #
      # Upload IPA
      #
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SwiftyTorrent-IPA
          path: SwiftyTorrent.ipa
